#!/bin/sh

case "$1" in
    start)
        /etc/init.d/Teleloadbot start
        ;;
    stop)
        /etc/init.d/Teleloadbot stop
        ;;
    restart)
        /etc/init.d/Teleloadbot restart
        ;;
    status)
        /etc/init.d/Teleloadbot status
        ;;
    enable)
        /etc/init.d/Teleloadbot enable
        echo "Enable Teleload auto-start."
        ;;
    disable)
        /etc/init.d/Teleloadbot disable
        echo "Disable Teleload auto-start."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|enable|disable}"
        exit 1
        ;;
esac
