#!/bin/sh /etc/rc.common

# This is the OpenWRT init.d script for Teleload

START=99  # 设置启动顺序，数字越大越后启动
STOP=10   # 设置停止顺序，数字越小越先停止

# 脚本描述
description="Teleload"

# 设置工作目录和执行文件路径
WORKING_DIR="/mnt/mmc1-1/Teleload"
EXEC_PATH="$WORKING_DIR/Teleload"

# 启动函数
start() {
    echo "Starting Teleload..."
    # 切换到工作目录并执行程序
    cd $WORKING_DIR
    $EXEC_PATH &
}

# 停止函数
stop() {
    echo "Stopping Teleload..."
    # 查找并杀死进程
    killall Teleload
}

# 重启函数
reload() {
    stop
    start
}
